Fix errors caused by deletion alert when deleting users
Refs #1778

TypeError: t.showDeletionAlert is not a function
  at onSuccess(./src/forum/utils/UserControls.js:104:12)